### ISSUE TITLE
Lion's Head

### ISSUE THREAD

**Issue by Fruitymo** [runningdeveloper/trails-data#1]
Added New Lion's Head Trail, Western Cape

**Comment by runningdeveloper** [comment]
Thank you please go ahead with the pull request.

**Comment by runningdeveloper** [comment]
@all-contributors please add @Fruitymo for adding a trail

**Comment by runningdeveloper** [comment]
@all-contributors please add @Fruitymo for adding data

**Comment by runningdeveloper** [comment]
@all-contributors please add @Fruitymo for content
